"use client";

import React, { useState, useEffect } from 'react';
import { Play, ArrowRight, Video, Loader2, X } from 'lucide-react';
import Link from 'next/link';

interface VideoItem {
  id: string;
  title: string;
  description: string;
  duration: string;
  thumbnail: string;
  category: string;
  videoUrl?: string;
}

const FALLBACK_VIDEOS: VideoItem[] = [
  {
    id: 'fv1',
    title: "How to apply for PM Surya Ghar Yojana?",
    description: "A complete step-by-step video guide to apply for the government subsidy.",
    duration: "5:20",
    thumbnail: "https://images.unsplash.com/photo-1613665813446-82a78c468a1d?q=80&w=2058&auto=format&fit=crop",
    category: "Guide"
  },
  {
    id: 'fv2',
    title: "Real Customer Review - Saving ₹3000/month",
    description: "See how Mr. Sharma from Patna eliminated his electricity bill completely.",
    duration: "4:15",
    thumbnail: "https://images.unsplash.com/photo-1548611635-b6e7827d7d4a?q=80&w=2070&auto=format&fit=crop",
    category: "Testimonial"
  },
  {
    id: 'fv3',
    title: "Understanding Solar Net Metering",
    description: "Learn how the grid credits you for excess solar energy generated by your panels.",
    duration: "7:45",
    thumbnail: "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?q=80&w=2070&auto=format&fit=crop",
    category: "Education"
  }
];

export function VideoBlog() {
  const [videos, setVideos] = useState<VideoItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeVideo, setActiveVideo] = useState<string | null>(null);

  useEffect(() => {
    fetch('http://localhost:5000/api/videos')
      .then(r => r.json())
      .then(data => {
        if (data.status === 'success' && data.data.length > 0) {
          setVideos(data.data.slice(0, 3));
        } else {
          setVideos(FALLBACK_VIDEOS);
        }
      })
      .catch(() => setVideos(FALLBACK_VIDEOS))
      .finally(() => setLoading(false));
  }, []);

  const displayVideos = videos.slice(0, 3);

  return (
    <section className="py-10 bg-white">
      <div className="container mx-auto px-4 max-w-6xl">
        <div className="flex flex-col md:flex-row justify-between items-end mb-12">
          <div className="max-w-2xl">
            <div className="inline-flex items-center gap-2 text-amber-500 font-bold mb-3 uppercase tracking-wide text-sm">
              <Video className="w-4 h-4" />
              <span>Learn &amp; Discover</span>
            </div>
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-extrabold text-slate-900 mb-4 leading-tight lg:whitespace-nowrap">
              Solar Insights &amp; <span className="text-amber-500">Video Guides</span>
            </h2>
            <p className="text-gray-600 text-lg">
              Watch our latest videos to understand the solar installation process, government schemes, and hear directly from our happy customers.
            </p>
          </div>
          <Link href="/our-work" className="hidden md:flex items-center gap-2 text-amber-500 font-bold hover:text-orange-600 transition-colors pb-2">
            View All Videos <ArrowRight className="w-5 h-5" />
          </Link>
        </div>

        {loading ? (
          <div className="flex items-center justify-center h-48">
            <Loader2 className="w-8 h-8 animate-spin text-amber-500" />
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {displayVideos.map((blog) => (
              <Link 
                href={blog.videoUrl || "/our-work"} 
                key={blog.id} 
                className="group cursor-pointer block" 
                onClick={(e) => {
                  if (blog.videoUrl) {
                    e.preventDefault();
                    setActiveVideo(blog.videoUrl);
                  }
                }}
              >
                {/* Thumbnail Container */}
                <div className="relative rounded-2xl overflow-hidden mb-4 shadow-md bg-slate-100 aspect-video">
                  <img
                    src={blog.thumbnail}
                    alt={blog.title}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                  <div className="absolute inset-0 bg-black/20 group-hover:bg-black/10 transition-colors duration-300"></div>

                  {/* Play Button Overlay */}
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="w-14 h-14 rounded-full bg-white/90 backdrop-blur-sm flex items-center justify-center text-amber-500 shadow-lg group-hover:scale-110 transition-transform duration-300">
                      <Play className="w-6 h-6 ml-1" fill="currentColor" />
                    </div>
                  </div>

                  {/* Duration Badge */}
                  {blog.duration && (
                    <div className="absolute bottom-3 right-3 bg-black/70 text-white text-xs font-bold px-2 py-1 rounded-md backdrop-blur-md">
                      {blog.duration}
                    </div>
                  )}

                  {/* Category Badge */}
                  {blog.category && (
                    <div className="absolute top-3 left-3 bg-amber-500 text-white text-xs font-bold px-3 py-1 rounded-full shadow-sm">
                      {blog.category}
                    </div>
                  )}
                </div>

                {/* Content */}
                <div>
                  <h3 className="font-bold text-xl text-slate-900 mb-2 group-hover:text-amber-500 transition-colors line-clamp-2">
                    {blog.title}
                  </h3>
                  <p className="text-gray-600 text-sm line-clamp-2">
                    {blog.description}
                  </p>
                </div>
              </Link>
            ))}
          </div>
        )}

        <div className="mt-8 text-center md:hidden">
          <Link href="/our-work" className="inline-flex items-center gap-2 text-amber-500 font-bold bg-orange-50 px-6 py-3 rounded-xl hover:bg-orange-100 transition-colors">
            View All Videos <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </div>

      {/* Video Modal */}
      {activeVideo && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/90 backdrop-blur-sm p-4">
          <button 
            onClick={() => setActiveVideo(null)} 
            className="absolute top-4 right-4 md:top-8 md:right-8 w-12 h-12 bg-white/10 hover:bg-white/20 rounded-full flex items-center justify-center text-white transition-colors"
          >
            <X className="w-6 h-6" />
          </button>
          
          <div className="w-full max-w-5xl aspect-video bg-black rounded-2xl overflow-hidden shadow-2xl relative">
            {activeVideo.includes('youtube.com') || activeVideo.includes('youtu.be') ? (
              <iframe 
                src={activeVideo.replace('watch?v=', 'embed/').replace('youtu.be/', 'youtube.com/embed/')} 
                className="w-full h-full" 
                allow="autoplay; encrypted-media; picture-in-picture" 
                allowFullScreen
              />
            ) : (
              <video 
                src={activeVideo} 
                className="w-full h-full" 
                controls 
                autoPlay 
              />
            )}
          </div>
        </div>
      )}
    </section>
  );
}
